WIP: Add Linter
Unity-Technologies/ROS-TCP-Connector pull request #103
Opened 2021-05-20 19:04 UTC by sdiao

## Proposed change(s)

Add dotnet format linter 
Pending: Add pre-commit hook to reformat code automatically.

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

Inspired by: 
https://github.com/dotnet/format
ML-Agents linter setup: https://github.com/Unity-Technologies/ml-agents/pull/4362

### Types of change(s)

- [ ] Bug fix
- [ ] New feature
- [x] Code refactor - formatting
- [ ] Documentation update
- [x] Other (please describe) - add linter to the repo

## Testing and Verification

Please describe the tests that you ran to verify your changes. Please also provide instructions, ROS packages, and Unity project files as appropriate so we can reproduce the test environment. 

### Test Configuration:
- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]

## Checklist
- [ ] Ensured this PR is up-to-date with the `dev` branch
- [ ] Created this PR to target the `dev` branch
- [ ] Followed the style guidelines as described in the [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the documentation as appropriate

## Other comments

2021-05-21 00:13 UTC, sdiao commented on .editorconfig
> +; see http://editorconfig.org/ for docs on this file
Inspired by ML-Agents repo's config. We are using dotnet format to format C# code.

2021-05-21 00:14 UTC, sdiao commented on .pre-commit-config.yaml
> +repos:
Key pre-commit config setup.

2021-05-21 00:16 UTC, sdiao commented on README.md
> -1. Using Unity 2020.2 or later, open the package manager from `Window` -> `Package Manager` and select "Add package from git URL..."
markdown files format are fixed automatically.  Instruction to set up: https://pre-commit.com/
To try it out locally, run `pre-commit run --files *.md`
![Screen Shot 2021-05-20 at 5 15 37 PM](https://user-images.githubusercontent.com/1437228/119063906-04fbba00-b98f-11eb-9342-1769715ad1f2.png)

2021-05-21 00:25 UTC, sdiao commented on .github/workflows/pre-commit.yml
> +            - uses: pre-commit/action@v2.0.0
Inspired by ML-Agents team's config. We are adding a Github Check here, so that once a pull request is opened, Github will run the pre-commit check as well. 

[Success check example](https://github.com/Unity-Technologies/ROS-TCP-Connector/runs/2635081540?check_suite_focus=true)
[Failed check example](https://github.com/Unity-Technologies/ROS-TCP-Connector/runs/2634918403?check_suite_focus=true)

2021-05-21 18:34 UTC, mrpropellers requested changes

2021-05-21 18:34 UTC, mrpropellers commented on ROSGeometry.md
> +    Vector3 unityPos = rosPos.toUnity;
Our example code should follow conventions too, in this case. Use `var` for these allocations instead of explicit type declarations (they're implied) and avoid overloaded abbreviations (`pos` could mean "position," "positive," "point of service"...)

2021-05-21 18:34 UTC, mrpropellers commented on ROSGeometry.md
> +	ros.Send("imu", msg);
use `var` and a more descriptive name than `msg` (note: `msg` abbreviation is ok)

2021-05-21 18:34 UTC, mrpropellers commented on ROSGeometry.md
> +    Vector3<FLU> rosPos = p.As<FLU>();
`var`

2021-05-21 18:34 UTC, mrpropellers commented on ROSGeometry.md
> +    void SubscriberCallback(Point p)
use descriptive function name

2021-05-21 18:34 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/PregeneratedMessages/Geometry/msg/MTwistWithCovariance.cs
>                  listOfSerializations.Add(BitConverter.GetBytes(entry));
Are these changes from the linter?  It's going to cause a lot of headache if the linter is modifying our generated code.  The message generation logic needs to be changed to output properly formatted code before this can go in. Otherwise we have two automated systems that will fight each other.

2021-05-21 18:56 UTC, sdiao commented on ROSGeometry.md
> +	ros.Send("imu", msg);
Would it be good to keep this PR only adding the linter and formatting? Happy to open a separate PR to update the sample code in markdown files.

2021-05-21 19:01 UTC, sdiao commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/PregeneratedMessages/Geometry/msg/MTwistWithCovariance.cs
>                  listOfSerializations.Add(BitConverter.GetBytes(entry));
Yes, the formatting changes is done by the linter. How often are pre-generated message updated? If it is not very often, I think we can merge this PR while fixing the message generation code.

2021-05-21 19:56 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/PregeneratedMessages/Geometry/msg/MTwistWithCovariance.cs
>                  listOfSerializations.Add(BitConverter.GetBytes(entry));
Yeah, not very often. That seems reasonable.

2021-05-21 21:01 UTC, sdiao commented on .editorconfig
> +insert_final_newline = false
Tracked in AIRO-698, which will be set up in a separate PR.

2021-05-24 17:48 UTC, sdiao commented on ROSGeometry.md
> +	ros.Send("imu", msg);
Looks we already have a task AIRO-667 to update the doc. Doc changes will be made in a separate PR.

2021-05-24 17:49 UTC, sdiao commented on ROSGeometry.md
> +    void SubscriberCallback(Point p)
Will be addressed in AIRO-667

2021-05-24 17:50 UTC, sdiao commented on ROSGeometry.md
> +    Vector3<FLU> rosPos = p.As<FLU>();
Doc will be updated in AIRO-667

2021-05-24 22:40 UTC, sdiao commented on ROSGeometry.md
> +    Vector3 unityPos = rosPos.toUnity;
The doc update will be addressed in AIRO-667

2021-05-24 23:24 UTC, peifeng-unity approved these changes
LGTM

2021-05-25 17:40 UTC, mrpropellers commented on ROSGeometry.md
> +	ros.Send("imu", msg);
Ok when I expand the code I can see that this "addition" is really just moving it around.  Our current rule is that if the code is new, or if you are re-writing older code for some reason, it must be changed to follow the coding standards if it doesn't already.  Since this is technically a change and not a move, it's ok to defer.

2021-05-25 17:40 UTC, mrpropellers approved these changes

2021-05-25 19:00 UTC, merged