Dev
Unity-Technologies/ROS-TCP-Connector pull request #142
Opened 2021-07-20 07:28 UTC by P3TE

## Proposed change(s)

Using a Unity Camera and a provided HeaderMsg, generate a corresponding CameraInfoMsg, see:
[CameraInfo Generator](https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/133)

### Types of change(s)

- [ ] Bug fix
- [X] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Ran sequences of images through stereo_image_proc and compared the point cloud output with the actual distances.

### Test Configuration:
- Unity Version: [Unity 2021.1.14f1]
- Unity machine OS + version: [Ubuntu 18.04]
- ROS machine OS + version: [Ubuntu 18.04, ROS Melodic]
- ROS–Unity communication: [ROS-TCP-Endpoint]

## Checklist
- [X] Ensured this PR is up-to-date with the `dev` branch
- [X] Created this PR to target the `dev` branch
- [X] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [X] Updated the [Changelog](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

2021-07-20 07:28 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=142) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: p3te<br/>:x: P3TE<br/><hr/>**p3te** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ROS-TCP-Connector?pullRequest=142) it.</sub>

2021-07-20 20:57 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
Hmm, MessageGeneration is clearly the wrong namespace to put this in, but there's not an obvious preexisting place either. It probably just belongs in ROSTCPConnector, with the hud etc.

2021-07-20 22:42 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
What about ROSGeometry?  This is a coordinate conversion of sorts. We could potentially rename ROSGeometry to ROSConversions, ROSAdapters or something similar if there's a way to deprecate ROSGeometry without causing too much user pain.

2021-07-20 22:49 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
I suggest we call it MessageUtilities, then.

2021-07-20 22:50 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
Oh, and if we're changing it anyway, I would be in favor of removing the ROSGeometry namespace and just moving those classes into Unity.Robotics.ROSTCPConnector.

2021-07-20 23:16 UTC, mrpropellers requested changes
Looks pretty good, but needs a style pass and some minor changes.  You can install an editor config to get automatic style linting in your IDE [here](https://github.com/Unity-Technologies/com.unity.coding), or there is a public copy of Unity's style reference sheet [here](https://github.com/Unity-Technologies/microgame-template/blob/dev/Docs/CSharpReference.cs).

2021-07-20 23:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            //Source http://ksimek.github.io/2013/08/13/intrinsic/
Good citations!

2021-07-20 23:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            /*
Avoid using block comments (`/* ... */`), especially mid-function. This whole thing should be commented with line comments instead, but more realistically you don't need to provide the full breakdown here. It's sufficient to provide the equation that you're using to calculate t_X and t_Y from and link to a reference if you think the reader might need more information about the implementation.

2021-07-20 23:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            double s = 0.0; //Axis Skew, Assuming none.
No in-line comments! Good call-out on the assumption being made here, but this should go on the line above

2021-07-20 23:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            cameraInfo.distortion_model = "plumb_bob";
`"plumb_bob"` should get assigned to a constant class member named something like `k_PlumbBob`, `k_PlumbBobDistortionModel`, or similar.

2021-07-20 23:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +        public static float GetVerticalFieldOfView(Camera camera)
This could be marked `private` or `internal`

2021-07-20 23:25 UTC, LaurieCheers-unity commented
> You can install an editor config to get automatic style linting in your IDE [here](https://github.com/Unity-Technologies/com.unity.coding), or there is a public copy of Unity's style reference sheet [here](https://github.com/Unity-Technologies/microgame-template/blob/dev/Docs/CSharpReference.cs).

Both of those are private repos. I don't think we have a public coding standards doc right now.

2021-07-20 23:39 UTC, P3TE commented
@LaurieCheers-unity, yes, It seems that I don't have access to those links.
I can use the [link in the CONTRIBUTING.md](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions) for code style for the time being.
Also, I'll start addressing the requested changes.

2021-07-20 23:47 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            uint resolutionHeight = (uint) pixelRect.height;
I don't usually use var, how do you decide what is the threshold for sufficiently implied?
In the above example, there are 4 lines where you could use var, which of these would you choose to?

2021-07-21 00:25 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
Is this something you would like me to do, or should I leave it as is, to be changed by you guys later?

2021-07-21 16:41 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +namespace Unity.Robotics.ROSTCPConnector.MessageGeneration
Given we don't have a coding standard we can actually show you, we should probably take it from here. Thanks.

2021-07-21 16:44 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            uint resolutionHeight = (uint) pixelRect.height;
Our standard is to use var if and only if the type is explicitly called out in the code - usually because you're calling a constructor, or casting to a specific type (as on lines 44 and 45 here).

2021-07-21 18:36 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/CameraInfoGenerator.cs
> +            uint resolutionHeight = (uint) pixelRect.height;
Same with line 40. 43 is more personal preference and either is fine

2021-07-21 18:42 UTC, mrpropellers commented
> > You can install an editor config to get automatic style linting in your IDE [here](https://github.com/Unity-Technologies/com.unity.coding), or there is a public copy of Unity's style reference sheet [here](https://github.com/Unity-Technologies/microgame-template/blob/dev/Docs/CSharpReference.cs).
> 
> Both of those are private repos. I don't think we have a public coding style doc right now.

Hmmm.... that's really strange. com.unity.coding was meant to be our outward-facing code standard reference.  We may need to update some links in our contributor guidelines... I'll follow up internally to see if I can figure out if there's another guide we can refer to instead, but for this PR @P3TE I think you're safe to just address the style changes called out in the PR and the pre-commit hook!

2021-07-22 16:17 UTC, mrpropellers approved these changes

2021-07-23 17:39 UTC, merged