Implementing Publisher Latching, Publisher Queue Sizes & More
Unity-Technologies/ROS-TCP-Connector pull request #152
Opened 2021-08-04 05:00 UTC by P3TE

## Proposed change(s)

1. Implementing a queue_size and latch publish functionality, both in Unity and for ROS.
2. Implementing an optional message pooling system allowing to reuse allocated message data which can reduce GC calls.
3. Changing the Thread.Sleep in the writer thread to a ManualResetEvent so that it can be woken from it's sleep early to send new messages
4. Improving multi threading safety with additional locks in the ROSConnection.
5. Started to refactor some of the SysCommand code to a new class, ROSConnection is kinda big. This is something we can definitely discuss though because I'm not 100% satisfied with my refactor there.
6. Added a 'public static TimeMsg SimulationTime' getter in ROSConnection that can be called from any thread. This is useful for populating Header messages.

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

https://github.com/Unity-Technologies/ROS-TCP-Endpoint/issues/82

### Types of change(s)

- [X] Bug fix
- [X] New feature
- [X] Code refactor

## Testing and Verification

Please describe the tests that you ran to verify your changes. Please also provide instructions, ROS packages, and Unity project files as appropriate so we can reproduce the test environment.

### Test Configuration:
- Unity Version: [e.g. Unity 2021.1.14f1]
- Unity machine OS + version: [e.g. Ubuntu 18.04]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Melodic]

I've done some rough testing in my environment, but it's by no means comprehensive.

## Checklist
- [X] Ensured this PR is up-to-date with the `dev` branch
- [X] Created this PR to target the `dev` branch
- [ ] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [Changelog](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

## Other comments

There's a lot here. I do have a bit of a habit of dreaming up some features I would like and going for it. I'm prepared for lots of comments and lots of back and forth before this pull request is approved. Also if there's features that you don't think should be a part of the repo or the implementation doesn't fit with the design of the project, I'm open to discussion and changing the implementation.

2021-08-04 05:10 UTC, P3TE commented
A Note:
For the added getter in ROSConnection.cs:
`public static TimeMsg SimulationTime`

To make it thread safe, I couldn't access Time.*
So I added a private variable that is set in the FixedUpdate and Update of the ROSConnection.cs. When 'SimulationTime' is called, it gets the latest value of this private variable.
This means that for the time to be correct, the script execution order for ROSConnection.cs has to be before everything else.
Unfortunately, although I did some research on how to set this up automatically, I didn't find any good implementations.

The work around is to set it up manually for each project:
![Screenshot from 2021-08-04 15-05-56](https://user-images.githubusercontent.com/5887944/128125095-b9825045-a81f-4cab-be33-d64e2dccb533.png)

However, this doesn't seem like an ideal solution so if you have suggestions on how this could be done better, I'm all ears.

2021-08-04 23:31 UTC, mrpropellers commented
Hey @P3TE thanks for pushing this all up. Looks like you've been busy! I've got some pretty high-priority work to get done this week so it will likely take me a few days to go through all of this but a quick upfront note:  I read your note about a TimeMsg, which I'm assuming means you've added some sort of Time abstraction to handle `/clock` messages?  Handling `use_sim_time` correctly, and in general ensuring we get our simulation time management correct without messing up some of the implicitly time-based systems like Unity's physics and rendering loops is still an ongoing Big Design Discussion internally. I'll take a look and give more pointed feedback soon, but expect me to request some stuff to be outright removed if it's related to establishing a Time abstraction - that's a thing we're currently just asking users to handle in the way that's best for them in their own projects, until we can get a really solid official implementation released.

2021-08-04 23:50 UTC, P3TE commented
@mrpropellers Thanks for your feedback on Time. I think it may be best if I remove my changes around keeping track of time and generating the TimeMsg  that are in this pull request as it seems how that is handled is up for debate and I wasn't super happy with my implementation in the first place. I would be interested to see an official implementation down the line and I'll move my implementation to my local repo separate from this.

2021-08-12 22:16 UTC, mrpropellers commented
Hey @P3TE, sorry for the hold up! Been pretty heads down on a project that should show up on the Unity blog tomorrow :)  I'm going to start digging into this PR now - are there accompanying changes that need to be reviewed in the Endpoint code?

2021-08-12 23:45 UTC, P3TE commented
Hi @mrpropeller, no worries. Big project hey, would this have anything to do with ROS2? I'll have to keep my eye out for the blog post. Also yes there were some changes the the Endpoint code, they were pretty small but I should have made a pull request for those changes, so I've done that here:
https://github.com/Unity-Technologies/ROS-TCP-Endpoint/pull/88

2021-08-13 18:34 UTC, mrpropellers requested changes
This looks like it's in pretty good shape! Left a couple clarifying questions and a bunch of style change requests. Unfortunately we still don't have a good way to reference Unity's internal style conventions so I've mostly just had to call them out explicitly for now. I'm going to see if we can't add a reference to our hub sometime soon, though...

2021-08-13 18:34 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +            if (!MessagePoolEnabled)
Should this be an assert?  If someone has disabled message pooling, this function should never get called, right?

2021-08-13 18:34 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/SendsOutgoingMessages.cs
> +    public class SimpleDataSender : SendsOutgoingMessages
What's the expected use case for this class?

2021-08-13 18:34 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/SysCommand.cs
> +    public abstract class SysCommand
Thanks for moving this out!

2021-08-13 19:01 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +        private object dictionaryLock = new object();
It is weird, but the C# lock() keyword just takes any object. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement

2021-08-13 19:07 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +                //IE: if (!m_Publishers.ContainsKey(rosTopicName)) error unregistered topic!
He means the code that's currently in Dev branch, which will log an error if you try to publish a message that hasn't been registered.
Yes, let's maintain that behavior.

2021-08-13 20:12 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        }
Yeah, this should be receiving a string RosMessageName.

2021-08-13 22:16 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        }
Ok for clarity it should look something like this:
```
using ROSTCPConnector.MessageGeneration;

public override bool IsType(string messageName)
{
    return messageName == MessageRegistry.GetRosMessageName<T>();
}
```
Any message classes that have been generated in the Project are automatically registered to the MessageRegistry.

2021-08-16 01:06 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //If this is non 0, a SendTo call will decrement the counter instead of sending data.
The main idea here is that I wanted to maintain that the order that data is published is maintained.
It's kind of impossible if you're dropping messages when the queue is full, so I have implemented a compromise.
With this new system, when you publish something, you add a placeholder in global queue (m_OutgoingMessageQueue). The sender thread will grab new messages to send by extracting these placeholders from the global queue. At this point either the placeholder contains a reference to the data to send so it will send it, or a flag that indicates that the data that was going to be sent here was removed from it's local queue (Because the local queue filled up before the data could be sent). The queueOverflowUnsentCounter is used to represent for the local queue that a message was removed before it could be sent.
When the sender thread asks for the latest message to send from a publisher, if the queueOverflowUnsentCounter is greater than zero, instead of sending data, it will decrement the counter and continue to the next publisher.
With this implementation, although you are dropping messages, all messages published in ROS will still be in the order in which they were queued to be sent.

2021-08-16 01:21 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //Whether you want to pool messages for reuse (Used to reduce GC calls).
Mainly convenience. Using message pooling only makes a noticeable difference for messages that contain a lot of data (IE an Image message); Without pooling, you can see additional GC calls in the profiler. For smaller messages such as an IMU or a NavSat message while pooling would mean less memory allocation in practice it's not such a big deal to just create new ones all the time and let the GC deal with it. I also wanted to maintain somewhat backwards compatibility with the previous workflow of just creating new messages and sending them. Also if you're using the pooling system, you don't (currently) have a way to call the message constructor of choice.

2021-08-16 02:06 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +            if (!MessagePoolEnabled)
I've never actually used an Assert before. I'll give it a go now.

2021-08-16 02:50 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/SendsOutgoingMessages.cs
> +    public class SimpleDataSender : SendsOutgoingMessages
Currently it is used for exclusively sys commands as they are handled slightly differently on the ros side. Maybe it would be worth renaming this to match, what do you think?

2021-08-16 03:15 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //first message in the queue is recycled and the message to publish is put on the end of the queue.
I think this is consistent with the behavior with ROS, but I couldn't find any super good information on the implementation, I based it around this post: https://answers.ros.org/question/243855/how-do-publishersubscriber-message-queues-work/

2021-08-16 04:11 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +            s_RealTimeSinceStartup = Time.realtimeSinceStartup;
So this was actually to fix an issue in HUDPanel.cs:58 where I would queue a message in the RosConnection from a thread other than the main thread which would update the HUDPanel, and it would call Time.realtimeSinceStartup, but that would throw an error because it's not the main thread, so I'm storing this variable so it can grab this instead.

2021-08-16 06:38 UTC, P3TE commented
Hey, I've made changes based on your suggestions, there's still a little to clear up yet, so I've commented on those. Cheers

2021-08-16 22:35 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/SendsOutgoingMessages.cs
> +    public class SimpleDataSender : SendsOutgoingMessages
Hmm yeah I guess I can see the utility of keeping it generically named in case we ever want to send other non-ROS message data in a simple way, but since this is the only place `SimpleData` is used, it's not clear what it means.  I think I'm in favor of changing it to `SysCommand` sender or maybe `JsonStringSender` to make it more clear what kind of data we expect this class to process.

2021-08-16 22:38 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //Whether you want to pool messages for reuse (Used to reduce GC calls).
Ok - I'm a little wary of creating two code paths where one will suffice.  If it's just options for the sake of options, I'd rather we just switch to pooling everything. In terms of workflow I think we're mostly safe as long as there's no breaking changes to the interfaces the class is exposing. 

Can you elaborate a bit on what you mean by "message constructor of choice?"  My understanding is that every message only has a single constructor, and every Publisher publishes a single message.  Am I missing something?

2021-08-16 22:42 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +            s_RealTimeSinceStartup = Time.realtimeSinceStartup;
Right but what I'm asking here is do you know why it won't let you access Time.realtimeSinceStartup from a non-main thread? I don't 😅 but I would assume that protection is there for a reason, and so I'm wondering if this effectively mitigates the issue they're worried about, or if you're just going around the protection to do something someone working on UnityEngine code would rather you didn't?

2021-08-16 22:54 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //If this is non 0, a SendTo call will decrement the counter instead of sending data.
Ah ok after reading the link from your other comment I understand the logic here. By dropping messages from the front of the queue instead of the back, you ensure the oldest messages are being dropped, which is probably especially important when queue size is very small and publish times are long. This seems like a good implementation, then!

Does this effectively mean there's no upper bound on the size of the global queue, though? This might be a sort of conflict of interest, if someone is using queue sizes to enforce constraints on memory usage for data they know will back up.

2021-08-17 00:17 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //Whether you want to pool messages for reuse (Used to reduce GC calls).
For example, a TwistMsg has two auto generated constructors:
`
public TwistStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.twist = new TwistMsg();
        }

        public TwistStampedMsg(Std.HeaderMsg header, TwistMsg twist)
        {
            this.header = header;
            this.twist = twist;
        }
`
The empty constructor is used primarily when decoding a message from a byte[] (Subscriber), and the other constructor is typically used in Unity when generating the message.
However when using a pooling system, when asking for a new TwistMsg, you don't know whether the pool has an existing one available which you can reuse or another needs to be created. If a new one needs to be created, you can use what ever constructor you want. However, if one is to be reused, I don't think you can call the constructor anymore because it already has been constructed (correct me if I'm wrong here because that would make pooling more vesatile).
So yeah, that's the problem of the pooling system, if it were to be used exclusively it would render the second constructor pretty much useless...

2021-08-17 00:28 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //If this is non 0, a SendTo call will decrement the counter instead of sending data.
In theory, yes, the global queue can technically grow unbounded... Fortunately, I think in practice it won't be much of a problem!
Here's why:
1. The global queue is only storing references to OutgoingMessageSender and not full message data so the per-element data size is quite small.
2. When the global queue starts to fill up due to dropping messages from the individual publisher queues, when it gets the next OutgoingMessageSender from the global queue and that OutgoingMessageSender has dropped messages, it will essentially perform a no-op and remove that instance OutgoingMessageSender from the global queue (A message that was going to be published at this spot was dropped and won't be sent anymore) thus reducing global queue size quickly.

So yeah, I didn't find a good way to make the global_queue not unbounded, but I think in practice the queue size won't consume much memory even when messages are getting dropped.

2021-08-17 00:50 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //Whether you want to pool messages for reuse (Used to reduce GC calls).
Your description is slightly out of date, the third constructor is used for subscribers deserializing byte arrays now... and this is exactly the kind of performance concern that led me to add it.

```        private TwistMsg(MessageDeserializer deserializer)
        {
            this.linear = Vector3Msg.Deserialize(deserializer);
            this.angular = Vector3Msg.Deserialize(deserializer);
        }```

Here it feels like we'd want a fourth constructor, one that behaves like the first but asks the pooling system for its members instead of calling new directly?

2021-08-17 01:19 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //Whether you want to pool messages for reuse (Used to reduce GC calls).
Yeah, 
Or you could even go further by having only 1 empty private constructor that can only get called through something such as `Activator.CreateInstance<T>();` in the pooling system.
Private would make it so you can't mistakenly create one without pooling IE `new TwistStampedMsg()` would throw an error.
Then create a `Deserialize` in place of the third constructor and an `Encode`/`Populate` or something in place of the second constructor that takes the `Std.HeaderMsg header, TwistMsg twist` arguments and overrides the existing parameter values.

2021-08-17 01:40 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +            s_RealTimeSinceStartup = Time.realtimeSinceStartup;
Yeah, to be honest, I'm not sure why Time.realtimeSinceStartup isn't thread safe. I would have imagined that it could have been made a volatile readonly property that Unity internally updates, but alas, when you try to read it from another thread you get a nasty exception `UnityException: get_realtimeSinceStartup can only be called from the main thread.`.
Basically what I did here was a quick hack to stop the exception and didn't think about it too much XD. The real problematic code is HUDPanel:58 which could be replaced with a DateTime.Now instead which I believe can be accessed from any thread. It's a bit of a different variable though as realtimeSinceStartup is seconds since the game started.

2021-08-17 17:45 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +            s_RealTimeSinceStartup = Time.realtimeSinceStartup;
This looks very weird to me. ROSConnection.s_RealTimeSinceStartup already gets updated in the ROSConnection.Update function. Did you need to update it more frequently or something? FixedUpdate is specifically a callback that runs once per physics update (which are not evenly distributed in wallclock time, even though each one simulates a fixed duration). Is there a real physics-related reason to use a FixedUpdate here?

2021-08-17 23:45 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs
> +            s_RealTimeSinceStartup = Time.realtimeSinceStartup;
Yeah, "If the only goal was to get a more accurate "last sent message" time, that's just for the hud visualization; don't worry about it." was pretty much my thinking. I'll remove the FixedUpdate part of ROSConnection.cs

2021-08-19 00:06 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //If this is non 0, a SendTo call will decrement the counter instead of sending data.
I'm a little wary of Murphy's Law getting us here... we've had a user who is experiencing an intermittent issue at somewhere around the 8 hour mark of continuous runtime: https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/280. This probably wouldn't bite them since they're sending intermittent, low-frequency messages, but good to keep in mind that some people are using the connector in rather unexpected ways :)

Also feel free to click the button when you're ready for a re-review:
![image](https://user-images.githubusercontent.com/29758400/129987486-51485984-c8de-455b-8da0-55337c947f38.png)

2021-08-19 00:27 UTC, P3TE commented on com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSPublisher.cs
> +        //If this is non 0, a SendTo call will decrement the counter instead of sending data.
Cheers! Haven't actually used the re-review button before haha, I'll do that now.

2021-08-23 23:13 UTC, mrpropellers approved these changes
Hey, looks good! When you are ready, please be sure to squash merge into `dev`, and try to get both this and the endpoint changes pushed as close to each other as possible to avoid users potentially checking out one change without the other.

2021-08-31 18:10 UTC, mrpropellers commented
> @mrpropellers Hey, I just added a bug fix for a bug I found, should I request a re-review?

Hey @P3TE just wanted to check in. Are you having any issues with the PR that still need support from us?  You should be free to squash merge as soon as your branch is up-to-date. Let me know if you any additional help.

2021-08-31 23:48 UTC, P3TE commented
@mrpropellers No issue, I had just assumed that the whole squash merge thing was a task you guys did lol. What do I need to do to perform a squash merge? Will I have write permissions for the dev branch of the original repo now that you have approved the pull request?

2021-09-02 18:53 UTC, mrpropellers commented
> @mrpropellers No issue, I had just assumed that the whole squash merge thing was a task you guys did lol. What do I need to do to perform a squash merge? Will I have write permissions for these commits to the dev branch of the original repo now that you have approved the pull request?
> I see the message " Only those with write access to this repository can merge pull requests.", is the squash merge something I would do on my own fork before you can perform the PR?
> Just some workflow things I don't understand I guess.

Hmm this might honestly be an issue with how we've set up our repos, or an org-wide permissions thing I'm not aware of. I was under the impression that you can simply squash merge in stuff yourself, but if that's not the case then I can go ahead and do it now!

2021-09-02 18:53 UTC, merged