Laurie/msg gen browser
Unity-Technologies/ROS-TCP-Connector pull request #22
Opened 2020-12-08 00:23 UTC by LaurieCheers-unity

Created a nicer UI for building .msg and .srv files.
Just open RosMessageGeneration->Browse, tell it where your ROS src folder is, and then you can navigate around and click to build individual files or entire folders.

2020-12-08 17:48 UTC, at669 reviewed
this is great! a lot easier than having to navigate to multiple directories. 

- srv button says `msgs`
- button to generate directory of services doesn't work for me, but each individual one does
![Screen Shot 2020-12-08 at 10 45 23 AM](https://user-images.githubusercontent.com/31416491/101521029-7cd6aa80-3942-11eb-9c69-0f1932268a15.png)

2020-12-08 17:48 UTC, at669 commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +            inPath = EditorGUILayout.TextField("Input Path", inPath);
can this title be clarified so that this should be the top-level ROS workspace folder?

2020-12-08 18:01 UTC, LaurieCheers-unity commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +            inPath = EditorGUILayout.TextField("Input Path", inPath);
> this is great! a lot easier than having to navigate to multiple directories.

Thanks! Yeah I've had to regenerate the common_msgs folder a couple of times, this is definitely my attempt to make that less annoying :-)

The title could be clearer but I'm not sure what exactly to put - it doesn't have to be the top level workspace folder, just literally any folder that contains messages somewhere.

2020-12-09 17:53 UTC, mpinol commented
`MessageTokenizerException: Unexpected token '--- '. Did you mean '---' (ROS Service/Action seperator)?` Just ran into this error when trying to generate a service with a trailing space after the line break. Tested on `dev` and it looked like everything generated just fine.

2020-12-09 18:31 UTC, mrpropellers requested changes

2020-12-09 18:31 UTC, mrpropellers commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +                    buildLabel = (entry.numMsgs != null) ? "Build " + entry.numMsgs : null;
What does it mean for buildLabel to be null here?  Is that an error case?  Should it return?

2020-12-09 18:31 UTC, mrpropellers commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +        CachedEntry cacheRoot;
Some private variables are getting `private` labels and others aren't. They could also use a prefix to differentiate them from local variables. Standard Unity style would be to exclude `private` and use `m_CapsCase`

2020-12-09 18:31 UTC, mrpropellers commented on Runtime/MessageGeneration/MessageAutoGen.cs
> +            return hierarchy[hierarchy.Length - 3];
This seems to be making an assumption about a very specific file hierarchy inside the catkin_package. Message files can be pretty much anywhere, though, as long as they are declared correctly in the CMakeLists. The only guaranteed way to determine the package name is to find the package.xml or CMakeLists.txt at the package root and read it from there.

2020-12-09 20:11 UTC, LaurieCheers-unity commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +                    buildLabel = (entry.numMsgs != null) ? "Build " + entry.numMsgs : null;
That means this line doesn't have a "Build" button.

2020-12-09 20:14 UTC, LaurieCheers-unity commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +                if(buildLabel != null)
Could do, I guess, but I wasn't envisioning it as a critical failure - I'd interpret it as meaning the cache system decided this should display as a file with no build button. At the moment we never do that, but we could.

2020-12-09 20:16 UTC, LaurieCheers-unity commented on Runtime/MessageGeneration/MessageAutoGen.cs
> +            return hierarchy[hierarchy.Length - 3];
Hmm, good to know. This is the logic we were already using to identify the package name... I guess it needs some revision.

2020-12-09 20:16 UTC, LaurieCheers-unity commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +        private HashSet<string> foldedOutHash;
Good idea.

2020-12-09 21:52 UTC, mrpropellers commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +                if(buildLabel != null)
Then perhaps a NotImplementedError would be appropriate?

2020-12-09 22:14 UTC, LaurieCheers-unity commented on Editor/MessageGeneration/MessageGenBrowser.cs
> +                if(buildLabel != null)
Ok, I added a "hasBuildButton" property to clarify the logic, see what you think.

2020-12-09 23:37 UTC, mrpropellers commented on Runtime/MessageGeneration/MessageAutoGen.cs
> +            return hierarchy[hierarchy.Length - 3];
Is that logic on the way in this review or coming in a follow-up task?

2020-12-10 00:20 UTC, LaurieCheers-unity commented on Runtime/MessageGeneration/MessageAutoGen.cs
> +            return hierarchy[hierarchy.Length - 3];
Working on it now, but I feel like it could go in a separate PR

2020-12-11 19:09 UTC, merged