Added more ROS-TCP-Connector tests
Unity-Technologies/ROS-TCP-Connector pull request #235
Opened 2021-11-15 18:39 UTC by LaurieCheers-unity

2021-11-18 23:27 UTC, mrpropellers requested changes

2021-11-18 23:27 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/MessagePoolTests.cs
> +        public void CanAddMessageThenGetItOnce()
We have some [naming conventions](https://confluence.unity3d.com/display/AIRO/Testing+and+Testable+Code#TestingandTestableCode-NamingConvention) defined that these tests could follow, although right now the namespacing convention causes more problems than it solves I think, so I started a [discussion on it ](https://unity.slack.com/archives/CRKCE9JDP/p1637277398140800) to amend the convention to something that closer matches what you're already using here.

2021-11-18 23:27 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Unrelated to this PR, but this bites people a lot. Since `HeaderMsg` is already hand-written, what do you think about us adding an extra constructor inside each block that transparently calls the correct constructor when the wrong one is called?  Maybe with a warning that says "You used ROS1 constructor but this is ROS2" or something

2021-11-18 23:27 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Same deal here! No action req. for the PR but I could add a backlog ticket for it

2021-11-19 00:05 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Hmm, for the headers, it seems reasonable to just ignore the extra/missing parameter. But for TimeMsg (and DurationMsg) we'd be casting between uint and int which seems like a dangerous thing to do silently.

2021-11-22 18:53 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Agreed - that could be called out as well in the "Hey you used the constructor for the other ROS warning" -- 99% of the time I think it'd be a safe cast since time is not allowed to be negative in either version.

2021-11-22 19:37 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Hmm, judging by this thread a Duration is allowed to be negative, but a negative Time is illegal, because they want 0 to mean uninitialized.
https://github.com/ros2/rclcpp/issues/525

2021-11-22 19:38 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/MessagePoolTests.cs
> +        public void CanAddMessageThenGetItOnce()
Ok, to be clear then, what changes are you actually requesting?

2021-11-22 21:40 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/MessagePoolTests.cs
> +        public void CanAddMessageThenGetItOnce()
Two changes:
1. Change namespace to `UnitTests` (rest of the namespace will be inferred from the assembly name by TestRunner)
2. Change test function names to be more in line with `ActionTaken_ScenarioExercised_ResultExpected` -- so for this first one it would be something like `AddAndGet_OneMessage_ReturnsSameMessage`

2021-11-22 21:41 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Tests/Runtime/TFSystemTests.cs
> +#endif
Right and since they are different classes I think we're safe to cast one to the other - if we really wanted to we could throw an exception in the case of a negative int.  I'll put a ticket in the backlog for it

2021-11-29 23:18 UTC, mrpropellers approved these changes

2021-11-29 23:26 UTC, merged