Fix to image msg
Unity-Technologies/ROS-TCP-Connector pull request #247
Opened 2021-12-21 05:25 UTC by Macbull

## Proposed change(s)

Fixes incorrect step size for image message in ToImageMsg() function, which was causing error while trying to view Image topic in rqt, image_view and rviz.

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

Ref #246 

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Manually checked that image shows up in rqt for each format of texture. 

### Test Configuration:
- Unity Version: [Unity 2020.3.8f1]
- Unity machine OS + version: [Windows 10]
- ROS machine OS + version: [ubuntu desktop-lxde-vnc:focal, ROS Galactic]
- ROS–Unity communication: [Docker]

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [x] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Updated the [Changelog](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/dev/com.unity.robotics.ros-tcp-connector/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

## Other comments

2021-12-21 05:26 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ROS-TCP-Connector?pullRequest=247) it.</sub>

2022-01-11 19:38 UTC, mrpropellers requested changes
Hey @Macbull thanks for submitting this fix!  Requesting a small change to help make this snippet more "self-documenting."

2022-01-11 19:38 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/Extensions/MessageExtensions.cs
> +            int step = 4 * tex.width;
Can these values be left uninitialized here?  It seems like their assignment depends on the texture format, and the default assignments are handled in the switch statement, so whatever is assigned here gets discarded anyway, right?

2022-01-12 05:20 UTC, Macbull commented on com.unity.robotics.ros-tcp-connector/Runtime/Extensions/MessageExtensions.cs
> +            int step = 4 * tex.width;
True. I initialized it to follow existing pattern of line 702. I have updated code to leave both encoding and step uninitialized.

2022-01-12 18:49 UTC, merged

2022-01-12 18:51 UTC, mrpropellers commented
Thanks for the changes @Macbull! I'll shepherd this the rest of the way through.