Laurie/robotics menu
Unity-Technologies/ROS-TCP-Connector pull request #42
Opened 2021-01-07 23:22 UTC by LaurieCheers-unity

2021-01-11 21:30 UTC, mrpropellers requested changes

2021-01-11 21:30 UTC, mrpropellers commented on Runtime/TcpConnector/ROSConnection.cs
> +                    GameObject instance = new GameObject("ROSConnection");
We assume the ROSConnectionPrefab usually exists in the build, right?  With no prefab, a user is just getting whatever defaults are hard-coded in the ROSConnection component? This could probably use a warning that some unexpected behavior may be on the way.

2021-01-11 21:36 UTC, LaurieCheers-unity commented on Runtime/TcpConnector/ROSConnection.cs
> +                    GameObject instance = new GameObject("ROSConnection");
Good point, it's probably worth printing a warning in the console when that happens.

Hmm, also, for users who make a build and want to read their IP address from the command line or whatever, it would be nice to have a clear way of setting the parameters for a ROSConnection before it actually connects.

2021-01-11 23:31 UTC, mrpropellers approved these changes

2021-01-12 00:49 UTC, mpinol approved these changes

2021-01-12 00:49 UTC, merged