Fixing message name that should not take a capital first letter automatically
Unity-Technologies/ROS-TCP-Connector pull request #47
Opened 2021-01-12 15:50 UTC by flonou

This fixes a small issue where message name variable was capitalized when it shouldn't (making ros unable to recognize the message type)

2021-01-13 00:04 UTC, LaurieCheers-unity commented
Interesting. This logic was unchanged from ROS#: https://github.com/siemens/ros-sharp/blob/327c60be19bc6953104fb8c6df88d003f30f1dbb/Libraries/MessageGeneration/MessageParser.cs#L70 but I guess the difference is they don't use it for message importing...?

2021-01-13 00:56 UTC, LaurieCheers-unity commented
Could you provide more context about why this needed to change? ROS official guidance is that all message names should start with a capital letter: http://wiki.ros.org/ROS/Patterns/Conventions#line-39 so it feels like that's the "correct" fix.

2021-01-13 01:22 UTC, flonou commented
Indeed, they do say to use a capital first letter.
I just encountered the issue today using messages someone else wrote and ros was importing the message type with a lowercase on wsl2 side (because the filename first letter was lowercase) using catkin_make.
I guess lowercase first letter is bad practice but ros seems to not fail when encountering it so the best options might be :
- Display a warning when generating and capitalize
- Display a warning when generating and don't capitalize
- Don't capitalize

2021-01-20 20:05 UTC, mrpropellers requested changes

2021-01-20 20:05 UTC, mrpropellers commented on Runtime/MessageGeneration/MessageParser.cs
> +                this.rosMsgName = inFileName;
Could you add a Debug.LogWarning here to warn the user that the message name was not found and is being inferred from the filename?  That could help prevent some confusion in the future around what's happening here.

2021-01-25 11:19 UTC, flonou commented on Runtime/MessageGeneration/MessageParser.cs
> +                this.rosMsgName = inFileName;
I added a warning message, is that what you meant ?

2021-01-25 19:19 UTC, mrpropellers approved these changes

2021-01-25 19:19 UTC, mrpropellers commented on Runtime/MessageGeneration/MessageParser.cs
> +                this.rosMsgName = inFileName;
Yep looks good!

2021-01-25 19:36 UTC, LaurieCheers-unity requested changes
Should be merged into dev.

2021-01-29 01:28 UTC, mrpropellers approved these changes

2021-01-29 17:58 UTC, LaurieCheers-unity approved these changes

2021-01-29 17:58 UTC, merged