Laurie/visualizers merge2
Unity-Technologies/ROS-TCP-Connector pull request #60
Opened 2021-02-02 22:55 UTC by LaurieCheers-unity

2021-02-10 00:32 UTC, mrpropellers requested changes

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +                            TypeVisualizers.Add(messageType, (MessageVisualizerCreator)getCreator.Invoke(null, null));
This looks like a good spot to check for un-supported classes and throw an exception that explains why they can't do that.

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            TopicVisualizers.Add(topic, VisualizerCreators.GetCreatorTM<VisualizerType, MsgType>());
What's `TM`?  If it's not a universally known acronym it should be spelled out.

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            public static MessageVisualizerCreator GetCreatorTMU<VisualizerType, MsgType, UserData>(UserData userData)
Similarly, could this just be a polymorphism of `GetCreator<VisualizerType, MsgType>` since it has a different function signature?

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            public static MessageVisualizerCreator GetCreatorTM<VisualizerType, MsgType>()
Ah ok... TM is "TypeMessage?"  Does this need that suffix? seems like it's implied from the templating.

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +        private static class VisualizerCreators
Naming nit: This looks kind of like a Factory class, but I might be missing some nuance. Would it be inaccurate to call it a VisualizerFactory?

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizerDrawing.cs
> +    public class MessageVisualizerDrawing<T> : IMessageVisualizer<T> where T : Message
Does this imply there could be multiple IMessageVisualizer-inheriting classes for a given message type?

2021-02-10 00:32 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/RegisterVisualizerAttribute.cs
> +    public class RegisterVisualizerAttribute : System.Attribute
Naming nit: Most attributes I've seen seem to be a short descriptive word/phrase as opposed to an imperative (`AdjectiveAttribute`/`NounAttribute`/`AdjectiveNounAttribute` instead of `VerbNounAttribute`). Could this be renamed something like `MessageVisualizerAttribute` to be consistent with that pattern?

2021-02-10 00:35 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            TopicVisualizers.Add(topic, VisualizerCreators.GetCreatorTM<VisualizerType, MsgType>());
Figured it out a little later!

2021-02-10 17:47 UTC, LaurieCheers-unity commented on MessageVisualization.md
> +	public interface IMessageVisualizer<MessageType> where MessageType:Message
We could do that, but I also allow dynamically registering a visualizer with the MessageVisualizers.RegisterVisualizer function. Having them auto-register might interfere with that workflow.

2021-02-10 17:47 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/DebugDraw.cs
> +        public class Drawing
Gizmos only work in the editor.

2021-02-10 17:48 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            // find and register all classes with the VisualizeMessage attribute
Correct, thanks.

2021-02-10 17:52 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +        private static class VisualizerCreators
This class exists only so that I can access these functions with reflection (which requires the functions to be public) without making them visible outside the class. We can call it anything, I was thinking about calling it PrivateFunctions.

2021-02-10 17:53 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizerDrawing.cs
> +    public class MessageVisualizerDrawing<T> : IMessageVisualizer<T> where T : Message
Yes: for example you can have different visualizers for different topics, even when they use the same message type.

2021-02-10 17:54 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/RegisterVisualizerAttribute.cs
> +    public class RegisterVisualizerAttribute : System.Attribute
Could call it AutoRegisteredVisualizer?

2021-02-10 17:57 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            public static MessageVisualizerCreator GetCreatorTMU<VisualizerType, MsgType, UserData>(UserData userData)
Yeah, it could. I was having a hard time accessing these functions with reflection and wanted to make sure I was getting the right one. I guess I can take it off now.

2021-02-10 18:18 UTC, LaurieCheers-unity commented on MessageVisualization.md
> +	[RegisterVisualizer]
I don't believe so. It will log an error at runtime when it tries to construct it, though.

2021-02-10 18:26 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +        private static class VisualizerCreators
It's actually possible to access a private method via reflection as well: https://stackoverflow.com/a/135482 -- not sure if that is useful here.

2021-02-10 18:27 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/RegisterVisualizerAttribute.cs
> +    public class RegisterVisualizerAttribute : System.Attribute
Sounds good to me!

2021-02-10 18:29 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +            public static MessageVisualizerCreator GetCreatorTMU<VisualizerType, MsgType, UserData>(UserData userData)
Actually no, reflection doesn't like trying to refer to an overloaded generic function. The two functions need to have different names. I called them GetCreator and GetCreatorWithUserdata.

2021-02-10 18:41 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +                            TypeVisualizers.Add(messageType, (MessageVisualizerCreator)getCreator.Invoke(null, null));
Added.

2021-02-10 18:42 UTC, mrpropellers commented on MessageVisualization.md
> +	[RegisterVisualizer]
Right - that's what I'd hope we could avoid. The point of failure would be at the line of code where they inherited from an incompatible class, but they won't hit an exception until it's constructed. In this case, the exception they get will hopefully lead a user to figure out what they did wrong, but it'd be preferable to a) have the exception reference the actual line of code that needs to be changed or, if (a) isn't possible, b) have the exception message indicate as explicitly as possible what needs to be changed.  Maybe you could at least wrap attempts to construct visualizers in a try/catch to improve the default message?

2021-02-10 18:51 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +                            TypeVisualizers.Add(messageType, (MessageVisualizerCreator)getCreator.Invoke(null, null));
Could I get a "if inherits from MonoBehaviour/ScriptableObject, complain" here as well? :)

2021-02-10 18:53 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/MessageVisualizations.cs
> +        private static class VisualizerCreators
Oh, yeah, that simplifies things.

2021-02-10 19:21 UTC, mrpropellers approved these changes

2021-02-26 21:40 UTC, mrpropellers commented on MessageVisualization.md
> +- If your visualizer doesn't call MessageVisualizations.RegisterVisualizer, it won't get used.
Did this change from before? I thought there was an attribute you had to use.

2021-02-26 21:40 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/BasicVisualizer.cs
> +        public Color color;
I think this commit actually un-did the correct style that was there before. Public variables for classes in the Unity namespace are PascalCase, public variables in UnityEngine or UnityEditor namespaces are camelCase.

2021-02-26 21:40 UTC, mrpropellers commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/BasicVisualizer.cs
> +        string topicCopy;
Similarly, this should be m_TopicCopy.

2021-02-26 23:32 UTC, LaurieCheers-unity commented on MessageVisualization.md
> +- If your visualizer doesn't call MessageVisualizations.RegisterVisualizer, it won't get used.
Yeah I removed that. Now you have to place them in the scene.

2021-02-26 23:35 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/BasicVisualizer.cs
> +        public Color color;
Oh, I get it. Weird convention.

2021-02-26 23:36 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/BasicVisualizer.cs
> +        string topicCopy;
🤮 fine...

2021-02-27 00:39 UTC, LaurieCheers-unity commented on com.unity.robotics.ros-tcp-connector/Runtime/MessageVisualization/BasicVisualizer.cs
> +        string topicCopy;
I don't see much point fixing it on this version, so I've done a new standards pass on the latest version of the branch. Here's the PR. https://github.com/Unity-Technologies/ROS-TCP-Connector/pull/68

2021-04-15 21:58 UTC, closed without merging